# -*- coding: utf-8 -*-
"""Video_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVQxpBGbQgeB9PzTzAc1Gm5iQCV0txTt
"""

# # Motive AI Hackathon (Problem 2): Video Indexing & Search — HYBRID GRAPH + SEMANTIC SEARCH
#
# This notebook:
# - Loads **`video_features.tsv`** from the Motiverse S3 bucket.
# - Builds text descriptions using Claude on Bedrock.
# - Creates embeddings + FAISS index for fast semantic retrieval.
# - **Builds a Knowledge Graph** for structured data relationships.
# - Implements a **two-stage hybrid search**:
#   1. **Retrieve:** Fetches top semantic candidates using FAISS.
#   2. **Re-rank:** Uses the knowledge graph and a Claude-powered parser to boost the score of more precise matches.
# - Shows top results with **scores, video previews, and detailed descriptions**.

# %%
!pip -q install pandas pyarrow faiss-cpu sentence-transformers scikit-learn pyyaml boto3 networkx > /dev/null

# %%
import os, time, json, io, re, tempfile
from typing import List, Dict, Tuple

import numpy as np
import pandas as pd
import faiss
import networkx as nx  # Added for graph capabilities
import boto3
from botocore.exceptions import ClientError
from sentence_transformers import SentenceTransformer
from IPython.display import HTML, display
from base64 import b64encode

# =============================
# AWS credentials (provided by organizer)
# =============================
aws_access_key_id = 'AKIATZ3VHKADZNRWWAU7'
aws_secret_access_key = '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'
aws_region = 'us-east-1'

# =============================
# Config
# =============================
class Config:
    BUCKET = 'motiverse-2025-data'
    KEY_FEATURES = 'video_features.tsv'

    ARTIFACT_DIR = '/content/artifacts'
    RUN_DIR = os.path.join(ARTIFACT_DIR, 'runs', time.strftime('run_%Y%m%d_%H%M%S'))

    EMBED_MODEL = 'intfloat/e5-base-v2'

    # --- Search Configuration ---
    TOPK_RETRIEVAL = 50       # How many candidates to fetch from FAISS for re-ranking
    TOPK_FINAL = 3            # How many final results to display
    SEMANTIC_WEIGHT = 0.6     # Weight for the initial semantic score
    GRAPH_WEIGHT = 0.4        # Weight for the graph-based precision score

    # --- Claude Configuration ---
    USE_CLAUDE = True
    CLAUDE_MODEL = 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'

os.makedirs(Config.ARTIFACT_DIR, exist_ok=True)
os.makedirs(Config.RUN_DIR, exist_ok=True)

# =============================
# S3 and Video Rendering Helpers (Unchanged)
# =============================
def s3_client(service='s3'):
    return boto3.client(service, aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

def read_s3_tsv(bucket: str, key: str) -> pd.DataFrame:
    obj = s3_client('s3').get_object(Bucket=bucket, Key=key)
    return pd.read_csv(io.BytesIO(obj['Body'].read()), sep='\t')

def render_s3_video(camera_media_id: str, width=320):
    key = f"videos/{camera_media_id}.mp4"
    try:
        with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as tmp:
            tmp_path = tmp.name
            s3_client('s3').download_file(Config.BUCKET, key, tmp_path)
            with open(tmp_path, 'rb') as f:
                b64 = b64encode(f.read()).decode('utf-8')
            html = f"""<video width="{width}" controls><source src="data:video/mp4;base64,{b64}" type="video/mp4"></video>"""
            display(HTML(html))
    except Exception as e:
        print(f"[WARN] Could not render video {camera_media_id}: {e}")
    finally:
        try: os.remove(tmp_path)
        except Exception: pass

# =============================
# Description Builders (Unchanged)
# =============================
def claude_describe_row(row: pd.Series) -> str:
    # (Your claude_describe_row function here - assuming it's defined)
    # This is a placeholder for brevity
    return f"A driving event of type {row.get('event_type', 'N/A')} involving objects like {row.get('objects_seen', 'N/A')}."

# =============================
# Embeddings + FAISS (Unchanged)
# =============================
class Embedder:
    def __init__(self, name: str):
        self.model = SentenceTransformer(name)
    def encode(self, texts: List[str], is_query=False) -> np.ndarray:
        prefix = 'query: ' if is_query else 'passage: '
        texts = [prefix + (t or '') for t in texts]
        return self.model.encode(texts, convert_to_numpy=True, normalize_embeddings=True).astype('float32')

def build_faiss_index(vecs: np.ndarray) -> faiss.Index:
    index = faiss.IndexFlatIP(vecs.shape[1])
    index.add(vecs)
    return index

# =============================
# NEW: Knowledge Graph Builder
# =============================
def build_knowledge_graph(df: pd.DataFrame) -> nx.Graph:
    G = nx.Graph()
    print("Building Knowledge Graph...")
    for _, row in df.iterrows():
        video_id = str(row['camera_media_id'])
        G.add_node(video_id, type='video')

        # Add and link nodes for events, objects, etc., standardized to lowercase
        if pd.notna(row['event_type']):
            node = str(row['event_type']).lower().strip()
            G.add_node(node, type='event')
            G.add_edge(video_id, node)
        try:
            if pd.notna(row['objects_seen']):
                objects = json.loads(str(row['objects_seen']).replace("'", "\""))
                for obj in objects:
                    node = obj.lower().strip()
                    G.add_node(node, type='object')
                    G.add_edge(video_id, node)
        except:
            pass
    print(f"Knowledge Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges.")
    return G

# =============================
# NEW: Claude Query Parser
# =============================
def claude_parse_query(query: str) -> List[str]:
    """Uses Claude to extract key graph entities from a search query."""
    client = s3_client('bedrock-runtime')
    prompt = f"""
    From the user query, extract a list of key nouns and event types that can be used to search a database.
    Ignore generic words like 'video', 'show me', 'driving'. Standardize to singular form and lowercase.
    Return a simple JSON list of strings.

    Query: "show me vehicle rollovers involving a guardrail"
    Output: ["rollover", "guardrail"]

    Query: "videos with snow at night"
    Output: ["snow", "night"]

    Query: "{query}"
    """
    messages = [{'role': 'user', 'content': [{'text': prompt}]}]
    try:
        resp = client.converse(modelId=Config.CLAUDE_MODEL, messages=messages, inferenceConfig={'maxTokens': 128})
        text_resp = resp['output']['message']['content'][0]['text']
        return json.loads(text_resp[text_resp.find('['):text_resp.rfind(']')+1])
    except Exception as e:
        print(f"[WARN] Could not parse query with Claude, graph re-ranking will be skipped. Error: {e}")
        return []

# =============================
# Main Pipeline Builder
# =============================
def build_pipeline(df: pd.DataFrame) -> Dict:
    df['video_id'] = df['camera_media_id'].astype(str)

    # Generate descriptions (assuming Claude for best results)
    print("Generating video descriptions with Claude...")
    desc = [claude_describe_row(r[1]) for r in df.iterrows()]
    meta = pd.DataFrame({'video_id': df['video_id'], 'phrase': desc})

    # Build semantic search assets
    embedder = Embedder(Config.EMBED_MODEL)
    vecs = embedder.encode(meta['phrase'].tolist())
    index = build_faiss_index(vecs)

    # Build knowledge graph
    graph = build_knowledge_graph(df)

    return {'meta': meta, 'index': index, 'embedder': embedder, 'graph': graph, 'df': df}

# =============================
# NEW: Hybrid Search and Preview Logic
# =============================
def hybrid_search_and_preview(queries: List[str], assets: Dict):
    meta, index, embedder, graph, df = assets['meta'], assets['index'], assets['embedder'], assets['graph'], assets['df']

    for q in queries:
        print(f"\n=== Hybrid Search Query: \"{q}\" ===")

        # --- Stage 1: Semantic Retrieval ---
        q_vec = embedder.encode([q], is_query=True)
        scores, indices = index.search(q_vec, Config.TOPK_RETRIEVAL)

        candidates = []
        for score, idx in zip(scores[0], indices[0]):
            if idx < 0: continue
            candidates.append({
                'id': meta.iloc[int(idx)].video_id,
                'semantic_score': score
            })

        # --- Stage 2: Graph Re-ranking ---
        target_nodes = claude_parse_query(q)
        print(f"Parsed graph entities for re-ranking: {target_nodes}")

        re_ranked_results = []
        for cand in candidates:
            graph_matches = 0
            if target_nodes:
                for neighbor in graph.neighbors(cand['id']):
                    if neighbor in target_nodes:
                        graph_matches += 1
                graph_score = graph_matches / len(target_nodes)
            else:
                graph_score = 0

            # Combine scores
            final_score = (Config.SEMANTIC_WEIGHT * cand['semantic_score']) + \
                          (Config.GRAPH_WEIGHT * graph_score)

            re_ranked_results.append({**cand, 'graph_score': graph_score, 'final_score': final_score})

        # Sort by the new final score
        re_ranked_results.sort(key=lambda x: x['final_score'], reverse=True)

        # --- Display Top Results ---
        for result in re_ranked_results[:Config.TOPK_FINAL]:
            vid = result['id']
            phr = meta[meta['video_id'] == vid].phrase.iloc[0]

            print(f"Video {vid} | Final Score: {result['final_score']:.3f} (Semantic: {result['semantic_score']:.2f}, Graph: {result['graph_score']:.2f})")
            print(f"Tags: {phr}")

            render_s3_video(vid, width=300)

            # Display full description
            row = df[df['camera_media_id'].astype(str) == vid].iloc[0]
            desc = claude_describe_row(row) if Config.USE_CLAUDE else phr
            print(f"Description: {desc}\n")

# =============================
# Run Demo
# =============================
print('[INFO] Loading video_features.tsv from S3…')
df = read_s3_tsv(Config.BUCKET, Config.KEY_FEATURES)
print('[OK] DataFrame shape =', df.shape)

# Build all assets: FAISS index, Knowledge Graph, etc.
# Using a smaller subset for a quick demonstration
assets = build_pipeline(df.head(200))

example_queries = [
    'videos with snow',
    'night time driving',
    'vehicle rollovers involving a guardrail',
    'cracked windshield'
]

hybrid_search_and_preview(example_queries, assets)

# =============================
# Run Your Specific Queries
# =============================

# List of new input queries
your_queries = [
    "Find stop sign violations on Woodford Avenue.",
    "Show me Mary Johnson's tailgating videos",
    "Find videos with railroad crossing sign.",
    "Find hard cornering events on a rural road during overcast weather.",
    "Find collisions on a 2-lane road that hit a guardrail.",
    "Find videos where the vehicle hits a traffic cone.",
    "Find collision videos that exclude a deer hit.",
    "Find hard brakes in Los Angeles in March 2025.",
    "Find t-bone collision videos with a silver SUV."
]

# Run the hybrid search and display the results
# (Assuming the 'assets' dictionary has already been built by the previous cells)
hybrid_search_and_preview(your_queries, assets)

# ==============================================================================
# 0. SETUP AND IMPORTS
# ==============================================================================
!pip -q install pandas pyarrow faiss-cpu sentence-transformers scikit-learn pyyaml boto3 networkx > /dev/null

import os, time, json, io, re, tempfile
from typing import List, Dict

import numpy as np
import pandas as pd
import faiss
import networkx as nx
import boto3
from botocore.exceptions import ClientError
from sentence_transformers import SentenceTransformer
from IPython.display import HTML, display
from base64 import b64encode

# ==============================================================================
# 1. AWS CREDENTIALS AND CONFIGURATION
# ==============================================================================
# (No changes needed here if your credentials are correct)
aws_access_key_id = 'AKIATZ3VHKADZNRWWAU7'
aws_secret_access_key = 'CejRG5BQMwC8/8tW0YnmdwaOwLs0fpsqhEvoUZ9/'
aws_region = 'us-east-1'

class Config:
    BUCKET = 'motiverse-2025-data'
    KEY_FEATURES = 'video_features.tsv'
    EMBED_MODEL = 'intfloat/e5-base-v2'
    CLAUDE_MODEL = 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'
    TOPK_RETRIEVAL = 50
    TOPK_FINAL_DISPLAY = 3
    GRAPH_BONUS_WEIGHT = 0.5 # Weight of the bonus for a full graph match

# ==============================================================================
# 2. HELPER FUNCTIONS (WITH CRITICAL FIXES AND ENHANCEMENTS)
# ==============================================================================

def s3_client(service='s3'):
    return boto3.client(service, aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region)

def read_s3_tsv(bucket: str, key: str) -> pd.DataFrame:
    obj = s3_client('s3').get_object(Bucket=bucket, Key=key)
    df = pd.read_csv(io.BytesIO(obj['Body'].read()), sep='\t')
    df['camera_media_id'] = df['camera_media_id'].astype(str)
    return df

def render_s3_video(camera_media_id: str, width=320):
    key = f"videos/{camera_media_id}.mp4"
    try:
        with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as tmp:
            tmp_path = tmp.name
            s3_client('s3').download_file(Config.BUCKET, key, tmp_path)
            with open(tmp_path, 'rb') as f: b64 = b64encode(f.read()).decode('utf-8')
            display(HTML(f"""<video width="{width}" controls><source src="data:video/mp4;base64,{b64}" type="video/mp4"></video>"""))
    except Exception as e:
        print(f"[WARN] Could not render video {camera_media_id}: {e}")
    finally:
        if 'tmp_path' in locals() and os.path.exists(tmp_path):
            os.remove(tmp_path)

# --- CRITICAL FIX 1: HIGH-QUALITY DESCRIPTION GENERATION ---
def claude_describe_row(row: pd.Series) -> str:
    """Generates a rich, detailed description using the real Claude API."""
    client = s3_client('bedrock-runtime')
    prompt = f"Describe this road-facing dashcam video incident in a concise, detailed summary based on the following JSON features:\n{row.to_json()}"
    messages = [{'role': 'user', 'content': [{'text': prompt}]}]
    try:
        resp = client.converse(modelId=Config.CLAUDE_MODEL, messages=messages, inferenceConfig={'maxTokens': 256, 'temperature': 0.3})
        time.sleep(1) # IMPORTANT: Prevents API throttling
        return resp['output']['message']['content'][0]['text']
    except ClientError as e:
        print(f"[WARN] Bedrock API error: {e}. Falling back to a simple description.")
        time.sleep(1)
        return f"A driving event of type {row.get('event_type', 'N/A')}."

class Embedder:
    def __init__(self, name: str):
        self.model = SentenceTransformer(name)
    def encode(self, texts: List[str], is_query=False) -> np.ndarray:
        prefix = 'query: ' if is_query else 'passage: '
        return self.model.encode([prefix + (t or '') for t in texts], convert_to_numpy=True, normalize_embeddings=True).astype('float32')

def build_faiss_index(vecs: np.ndarray) -> faiss.Index:
    index = faiss.IndexFlatIP(vecs.shape[1])
    index.add(vecs)
    return index

# --- CRITICAL FIX 2: ENRICHED KNOWLEDGE GRAPH ---
def build_knowledge_graph(df: pd.DataFrame) -> nx.Graph:
    """Builds an enriched Knowledge Graph with location and other details."""
    G = nx.Graph()
    print("Building Enriched Knowledge Graph...")
    for _, row in df.iterrows():
        video_id = str(row['camera_media_id'])
        G.add_node(video_id, type='video')
        # Add nodes for event, street, city, and state
        for col in ['event_type', 'street_name', 'city', 'state']:
            if pd.notna(row.get(col)):
                G.add_edge(video_id, str(row[col]).lower().strip())
        # Add nodes for objects
        try:
            if pd.notna(row['objects_seen']):
                objects = json.loads(str(row['objects_seen']).replace("'", "\""))
                for obj in objects: G.add_edge(video_id, obj.lower().strip())
        except: pass
    print(f"Enriched Knowledge Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges.")
    return G

def claude_parse_query(query: str) -> List[str]:
    """Uses Claude to extract key graph entities from a search query."""
    client = s3_client('bedrock-runtime')
    prompt = f'From the user query, extract a list of key nouns and event types. Ignore generic words. Standardize to singular and lowercase. Return only a JSON list of strings.\nQuery: "{query}"'
    messages = [{'role': 'user', 'content': [{'text': prompt}]}]
    try:
        resp = client.converse(modelId=Config.CLAUDE_MODEL, messages=messages, inferenceConfig={'maxTokens': 128})
        text_resp = resp['output']['message']['content'][0]['text']
        return json.loads(text_resp[text_resp.find('['):text_resp.rfind(']')+1])
    except Exception as e:
        print(f"[WARN] Could not parse query with Claude. Error: {e}")
        return []

# =============================
# 3. Main Pipeline and Search Logic
# =============================
def build_pipeline(df: pd.DataFrame) -> Dict:
    df['video_id'] = df['camera_media_id'].astype(str)
    print("Generating high-quality video descriptions with Claude... This may take time.")
    # This assumes a pre-processed df with descriptions is passed in
    meta = pd.DataFrame({'video_id': df['video_id'], 'phrase': df['llm_description']})
    embedder = Embedder(Config.EMBED_MODEL)
    vecs = embedder.encode(meta['phrase'].tolist())
    index = build_faiss_index(vecs)
    graph = build_knowledge_graph(df)
    return {'meta': meta, 'index': index, 'embedder': embedder, 'graph': graph, 'df': df}

# --- CRITICAL FIX 3: SMARTER HYBRID SCORING ---
def hybrid_search_and_preview(queries: List[str], assets: Dict):
    meta, index, embedder, graph, df = assets['meta'], assets['index'], assets['embedder'], assets['graph'], assets['df']
    for q in queries:
        print(f"\n{'='*20}\nHybrid Search Query: \"{q}\"\n{'='*20}")
        # Stage 1: Semantic Retrieval
        q_vec = embedder.encode([q], is_query=True)
        scores, indices = index.search(q_vec, Config.TOPK_RETRIEVAL)
        candidates = [{'id': meta.iloc[int(idx)].video_id, 'semantic_score': score}
                      for score, idx in zip(scores[0], indices[0]) if idx >= 0]
        # Stage 2: Graph Re-ranking with Bonus Score
        target_nodes = claude_parse_query(q)
        print(f"Parsed graph entities for re-ranking: {target_nodes}")
        re_ranked_results = []
        for cand in candidates:
            graph_matches = sum(1 for neighbor in graph.neighbors(cand['id']) if neighbor in target_nodes)
            graph_score = graph_matches / len(target_nodes) if target_nodes else 0.0
            # NEW SCORING: Semantic score is the baseline, graph score provides a bonus
            final_score = cand['semantic_score'] + (Config.GRAPH_BONUS_WEIGHT * graph_score)
            re_ranked_results.append({**cand, 'graph_score': graph_score, 'final_score': final_score})
        # Sort by the new final score
        re_ranked_results.sort(key=lambda x: x['final_score'], reverse=True)
        # Display Top Results
        print("\n--- Top Search Results ---")
        for result in re_ranked_results[:Config.TOPK_FINAL_DISPLAY]:
            vid = result['id']
            phr = meta[meta['video_id'] == vid].phrase.iloc[0]
            print(f"Video {vid} | Final Score: {result['final_score']:.3f} (Semantic: {result['semantic_score']:.2f}, Graph Bonus: {result['graph_score']:.2f})")
            render_s3_video(vid)
            print(f"Description: {phr}\n")

# =============================
# 4. Run Demo
# =============================
# This assumes you have ALREADY run the full script from the previous turn to generate
# the cached CSV on your Google Drive. If not, you must run that script first.
GDRIVE_CACHE_PATH = '/content/drive/MyDrive/Colab Notebooks/video_features_with_descriptions.csv'

if os.path.exists(GDRIVE_CACHE_PATH):
    print(f"Loading pre-processed data from Google Drive...")
    df_processed = pd.read_csv(GDRIVE_CACHE_PATH)
    df_processed['camera_media_id'] = df_processed['camera_media_id'].astype(str)

    # Build all assets from the loaded data
    assets = build_pipeline(df_processed)

    # Your new list of queries
    your_queries = [
        "Find stop sign violations on Woodford Avenue.",
        "Show me Mary Johnson's tailgating videos",
        "Find videos with railroad crossing sign.",
        "Find hard cornering events on a rural road during overcast weather.",
        "Find collisions on a 2-lane road that hit a guardrail.",
        "Find videos where the vehicle hits a traffic cone.",
        "Find collision videos that exclude a deer hit.",
        "Find hard brakes in Los Angeles in March 2025.",
        "Find t-bone collision videos with a silver SUV."
    ]

    hybrid_search_and_preview(your_queries, assets)
else:
    print(f"ERROR: Cached file not found at '{GDRIVE_CACHE_PATH}'.")
    print("Please run the complete script from the previous step first to generate the descriptions and save the file to your Google Drive.")

